# Generated by Django 5.0.2 on 2024-03-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='media/empty.png', upload_to='media/'),
        ),
    ]
