# Generated by Django 5.0.2 on 2024-03-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='/media/empty.png', upload_to='media/'),
        ),
    ]
