# Generated by Django 5.0.2 on 2024-03-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_recipe_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestIng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/img_app/empty.png', upload_to='images/img_app/category')),
            ],
        ),
    ]
