# Generated by Django 5.0.2 on 2024-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
